### PR TITLE
#1519: Use Jp.qosearch in total_active_contributors.rb instead of direct search_commits

### LINKED ISSUE #1519: `total_active_contributors.rb` exhausts API limit by directly calling `Fbe.octo.search_commits`, bypassing `Jp.qosearch` and aborting `dimensions-of-terrain` cycle
`judges/dimensions-of-terrain/total_active_contributors.rb:12-14` calls `Fbe.octo.search_commits(...)` directly on every repo in `Fbe.unmask_repos`. The call has no `rescue` and is not routed through `lib/qos_search.rb`'s `Jp.qosearch` latch.

The GitHub Search API enforces a 30-requests-per-minute secondary rate limit independent of the core REST quota. `lib/qos_search.rb` was added to manage this exact constraint for `search_issues` callers: it reads `resources.search.remaining`, sets `@offquota` when the budget hits zero, and converts `Octokit::TooManyRequests` into a `warn` + `nil` return so the cycle continues. PR #1474 is currently moving `judges/find-all-issues/find-all-issues.rb` to this helper for the same reason. `total_active_contributors` is now the only remaining direct caller of any Search API method (`grep -rn "search_commits\|search_users\|search_repositories\|search_topics" judges/ lib/` returns only line 12 of this file). On a project with several dozen repositories the function exhausts the search budget within seconds, then a single `Octokit::TooManyRequests` bubbles past the enclosing `Fbe.unmask_repos` block and aborts the entire `dimensions-of-terrain` judge for the rest of the cycle.

Generalize `Jp.qosearch` in `lib/qos_search.rb` to dispatch on a method name (or add a sibling `Jp.qosearch_commits`) so this call can reuse the existing `@offquota` latch and the canonical `Octokit::TooManyRequests` rescue, then rewrite line 12 to call it. The contributors set should keep its current `id` filter, and the function should return the partial total when the latch trips rather than raising.

### PR DESCRIPTION
**Pull request by VasilevNStas**
Closes #1519

Generalized `Jp.qosearch` in `lib/qos_search.rb` to dispatch on `kind:` parameter (`:issues` or `:commits`). Existing callers continue to work unchanged (defaults to `:issues`).

Changed `total_active_contributors.rb` to use `Jp.qosearch(query, kind: :commits)` instead of calling `Fbe.octo.search_commits` directly, so the `@offquota` latch and `Octokit::TooManyRequests` rescue are reused.

## Verification
- `bundle exec rubocop` → 0 offenses ✅
- `bundle exec rake test` → 259 tests, 0 failures ✅

### CODE REVIEW

**Comment by VasilevNStas** [comment]
@yegor256 @edmoffo please review

**Review by GHX5T-SOL — CHANGES_REQUESTED** [review]
The implementation direction for #1519 looks right, but the new regression test is order-dependent. Running it directly fails before it reaches the code under test because `Jp.qoreset` is not defined until `lib/qos_search.rb` has been required, and this test calls it before `load_it` loads the dimension helper.

Repro:

```
bundle exec ruby -Itest test/judges/test-dimensions-of-terrain.rb -n test_total_active_contributors
```

This raises `NoMethodError: undefined method `qoreset` for module Jp` at `test/judges/test-dimensions-of-terrain.rb:662`. The full file and full suite pass only when some earlier test in the same process has already loaded `lib/qos_search.rb`, so the new test is not self-contained. Please require the helper before calling `Jp.qoreset`, or otherwise move the reset after the helper is loaded.

For context, the broader local checks were clean: `bundle exec rake test` passed (`259` tests, `678` assertions, `1` skip), and `bundle exec rubocop` passed (`101` files inspected).

**Comment by VasilevNStas** [comment]
Fixed: added require_relative('../../lib/qos_search') before Jp.qoreset call so the test is self-contained and works in isolation. @yegor256 @edmoffo @GHX5T-SOL please re-review

**Review by GHX5T-SOL — APPROVED** [review]
Reviewed current head `1c1b412e3a65401d5ce549e360792b4e4bd4208d`.

The earlier isolated-test failure is fixed: `test/judges/test-dimensions-of-terrain.rb` now requires `lib/qos_search` before calling `Jp.qoreset`, so `bundle exec ruby -Itest test/judges/test-dimensions-of-terrain.rb -n test_total_active_contributors` passes directly.

Local validation passed:

```
git diff --check origin/master...HEAD
ruby -c judges/dimensions-of-terrain/total_active_contributors.rb
ruby -c lib/pull_request.rb
ruby -c lib/qos_search.rb
ruby -c test/judges/test-dimensions-of-terrain.rb
ruby -c test/lib/test_pull_request.rb
bundle exec ruby -Itest test/judges/test-dimensions-of-terrain.rb -n test_total_active_contributors
bundle exec ruby -Itest test/lib/test_pull_request.rb -n '/test_comments_info_/'
bundle exec ruby -Itest test/judges/test-dimensions-of-terrain.rb
bundle exec rake test
bundle exec rubocop
```

Hosted checks are green as well. No findings on the revised head.
